name: konsul_dosen
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.2
  logger: ^2.0.2
  pretty_dio_logger: ^1.3.1
  equatable: ^2.0.5
  extended_image: ^8.1.1
  formz: ^0.6.0
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.2
  path_provider: ^2.1.1
  go_router: ^10.1.2
  intl: ^0.18.1
  flutter_native_splash: ^2.2.16
  responsive_framework: ^1.1.1
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  firebase_storage: ^11.7.5
  cloud_firestore: ^4.17.3
  image_picker: ^1.1.1
  permission_handler: ^11.0.0
  image_cropper: ^5.0.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
