// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcZ8tKMZ36bn7y7Xgw6QEXx6LtYu5gpao',
    appId: '1:666896413630:web:d28630a1eb19072b843fef',
    messagingSenderId: '666896413630',
    projectId: 'konsultasi-c1330',
    authDomain: 'konsultasi-c1330.firebaseapp.com',
    storageBucket: 'konsultasi-c1330.appspot.com',
    measurementId: 'G-0VK2SZL841',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsptU3GVvXaP-OAaZjoa50G3vLL_OwWpw',
    appId: '1:666896413630:android:0da0c11d9ebb87b6843fef',
    messagingSenderId: '666896413630',
    projectId: 'konsultasi-c1330',
    storageBucket: 'konsultasi-c1330.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFkTyrWYjRZPrrgYSJsz_B5-VlSO57aBU',
    appId: '1:666896413630:ios:9779742ddf122491843fef',
    messagingSenderId: '666896413630',
    projectId: 'konsultasi-c1330',
    storageBucket: 'konsultasi-c1330.appspot.com',
    iosBundleId: 'com.example.konsulDosen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFkTyrWYjRZPrrgYSJsz_B5-VlSO57aBU',
    appId: '1:666896413630:ios:9779742ddf122491843fef',
    messagingSenderId: '666896413630',
    projectId: 'konsultasi-c1330',
    storageBucket: 'konsultasi-c1330.appspot.com',
    iosBundleId: 'com.example.konsulDosen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcZ8tKMZ36bn7y7Xgw6QEXx6LtYu5gpao',
    appId: '1:666896413630:web:92c60a8585c1306c843fef',
    messagingSenderId: '666896413630',
    projectId: 'konsultasi-c1330',
    authDomain: 'konsultasi-c1330.firebaseapp.com',
    storageBucket: 'konsultasi-c1330.appspot.com',
    measurementId: 'G-CQYEJLMGX5',
  );
}
